### ISSUE TITLE
UnauthorizedAPICalls

### ISSUE THREAD

**Issue by kli-abine** [alertlogic/cwe-collector#76]
Please fix unauthorized API call issue

error event as follows:
```
{
  "eventSource": "cloudformation.amazonaws.com",
  "eventName": "DescribeStacks",
  "awsRegion": "us-east-1",
  "userAgent": "aws-sdk-nodejs/2.1185.0 linux/v14.19.3 exec-env/AWS_Lambda_nodejs14.x callback",
  "errorCode": "AccessDenied",
  "errorMessage": "User: arn:aws:sts::1234567890:assumed-role/Alertlogic-GuardDuty-CollectLambdaRole-Y7AG3E63UDK9/alertlogic-cwe-collector is not authorized to perform: cloudformation:DescribeStacks because no identity-based policy allows the cloudformation:DescribeStacks action",
  "readOnly": true,
  "eventType": "AwsApiCall"
}
```

**Comment by tomotway** [comment]
Am seeing this issue too.  From the cloudtrail log it looks like the call to cloudformation:DescribeStacks does not have any parameters (eg stack name) 

@imranalisyed506  I guess this error may be coming from code changes related to this pr?  https://github.com/alertlogic/cwe-collector/pull/75

**Comment by rakhimundhada15** [comment]
I am looking into it. Will update once i will fix and raised the pr.

**Comment by rakhimundhada15** [comment]
We have fixed the unauthorised issue getting while health checks. We have released the changes to production ,once collector updated to 1.3.13 version within 12 hr, issue will resolved.

**Comment by tomotway** [comment]
ok great, thanks @rakhimundhada15 , I will give it a test tomorrow

**Comment by kli-abine** [comment]
Thanks for solving this issue.
